- docs/index.html
This PR mirrors https://github.com/w3c-ccg/vc-http-api/pull/195
> chore: fix links

- docs/sections/authorization.html
> Refine Authorization Section

- README.md
- docs/index.html
- docs/sections/abstract.html
- docs/sections/api-spec.html
depends on pr #30 - gives us a good starting place that we can build on and resolves #12 and #13
> Encryption standards

- .github/workflows/ci.yml
- package.json
- packages/tests-postman/data/service-providers.json
- packages/tests-postman/index.js
- packages/tests-postman/package-lock.json
- packages/tests-postman/package.json
Update `ci.yml` action to include postman tests. Note that this PR is contingent on #73 being merged first.
FIX: #68
> Add CI to run postman tests

- packages/tests-postman/package-lock.json
- packages/tests-postman/package.json
Package ky-universal also requires package ky
> fix: add missing ky package

- .github/workflows/regression-revocation.yml
- docs/tutorials/.gitignore
- docs/tutorials/revocation/README.md
- docs/tutorials/revocation/revocation.collection.json
This PR adds authenticated credential revocation tests
> Add revocation test

- .github/workflows/regression-vc-jwt.yml
- docs/tutorials/vc-jwt/README.md
- docs/tutorials/vc-jwt/vc-jwt.collection.json
We opted to unwind an ill-advised attempt at storing VC_JWT in a form other then the compact JWT representation.
> Add vc-jwt example

- .github/workflows/regression-agility.yml
- .github/workflows/regression-exchange.yml
- .github/workflows/regression-mtrc.yml
- .github/workflows/regression-revocation.yml
- .github/workflows/regression-vc-jwt.yml
Fix issues with unkown reporter `jsonname` when running newman tests from the command-line for github workflows.
FIX: #110
> fix: clear syntax issue with newman CLI tests

- docs/tutorials/revocation/revocation.collection.json
Replace hard-coded server name in DID resolution request with environment variable.
FIX: 113
> fix: remove hard-coded server name from test

- docs/components/VerificationResult.yml
- docs/tutorials/authentication/README.md
- docs/tutorials/authentication/authentication-tutorial.collection.json
- docs/tutorials/mill-test-report-certificate/vc-api.mtrc.collection.json
- docs/tutorials/revocation/revocation.collection.json
- docs/tutorials/vc-jwt/vc-jwt.collection.json
> Remove references to "checks" in verification response assertions

- docs/index.html
- docs/openapi/openapi.json
- docs/openapi/openapi.yml
- docs/openapi/resources/presentations.yml
- docs/sections/authorization.html
This PR adds example OAuth2 configuration, it's related to a number of issues.
Linked issues:
- https://github.com/w3c-ccg/traceability-interop/issues/124
- https://github.com/w3c-ccg/traceability-interop/issues/95
Additional links related to scopes:
- https://cloud.google.com/storage/docs/authentication
- https://auth0.com/docs/get-started/apis/scopes
- https://developers.google.com/identity/protocols/oauth2/scopes
We should consider fine grained scopes, previously we had looked at:
```
scopes:
'create:credentials': Grants permission to create credentials
'derive:credentials': Grants permission to derive credentials
'create:presentations': Grants permission to create presentations
'verify:presentations': Grants permission to verify presentations
'exchange:presentations': Grants …
```
> Add security

- .github/workflows/regression-agility.yml
- .github/workflows/regression-credentials-issue.yml
- .github/workflows/regression-credentials-verify.yml
- .github/workflows/regression-did-web-discovery.yml
- .github/workflows/regression-exchange.yml
- .github/workflows/regression-mtrc.yml
- .github/workflows/regression-revocation.yml
- .github/workflows/regression-vc-jwt.yml
All providers who have created test related secrets should be included in test matrix for unit testing.
> Add all providers to test matrix

- docs/tutorials/credentials-issue/credentials-issue.postman_collection.json
> remove revocation suite from baseline issuance

- .github/workflows/regression-workflow-instance-join.yml
Fixing my own collection workflow
> fix: collection path

- docs/tutorials/credentials-revocation/credentials-revocation.postman_collection.json
> add revocation context, fix issue expected response

- docs/tutorials/credentials-verify/credentials-verify.postman_collection.json
Test for details verification checks. 
Ref https://github.com/w3c-ccg/traceability-interop/pull/168.
> feat: detailed verification check

- docs/tutorials/presentations-exchange/presentations-exchange.postman_collection.json
This test was incorrect, so removing it.
> fix: removing aka match baseurl test

- .github/workflows/authentication-tutorial.yml
- .github/workflows/interoperability-report.yml
- .github/workflows/regression-agility.yml
- .github/workflows/regression-mtrc.yml
- .github/workflows/regression-vc-jwt.yml
> test: remaining tests switched to production

- docs/openapi/resources/presentation-prover.yml
> fix: update referenced response schema for presentation/prove

- .github/workflows/interoperability-report.yml
Adds revocation tutorial to interop
> adds revocation to interop report

- docs/openapi/resources/credential-issuer.yml
- docs/openapi/schemas/IssueCredentialOptions.yml
Update credentials/issue request to make "credential" and "options.type" required.
FIXES: #227
> fix: update "required" portions of credentials/issue request

- environment-setup/README.md
- environment-setup/github_secrets.sh
- environment-setup/sample.env
> convenience script

- docs/index.html
Intro to interop testing
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/traceability-interop/pull/231.html" title="Last updated on May 23, 2022, 9:55 AM UTC (6c49d29)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/traceability-interop/231/6a854bc...6c49d29.html" title="Last updated on May 23, 2022, 9:55 AM UTC (6c49d29)">Diff</a>
> docs: CI testing intro

- docs/discovery.md
Removing the todo of https://github.com/w3c-ccg/traceability-vocab/pull/412. Merge the trace-vocab PR first.
> `TraceabilityAPI` Term Definition

- docs/index.html
Updating the spec to reflect the tests.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/traceability-interop/pull/254.html" title="Last updated on Jun 16, 2022, 12:23 AM UTC (0d0e636)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/traceability-interop/254/4e76cd5...0d0e636.html" title="Last updated on Jun 16, 2022, 12:23 AM UTC (0d0e636)">Diff</a>
> Update to clarify revocation list to match tests

- docs/openapi/resources/presentation-prover.yml
- docs/openapi/resources/presentation-verifier.yml
- docs/openapi/schemas/PresentationOptions.yml
- docs/openapi/schemas/proofType.yml
Apply slight fix to presentation-prover modifications to fix regression, and apply same fix to presentation-verifier.
Reference #230
> fix: repair regression in openapi build

- docs/index.html
Reference #254
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 17, 2022, 8:24 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fw3c-ccg%2Ftraceability-interop%2Fpull%2F256%2F78dd639.html&doc2=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fw3c-ccg%2Ftraceability-interop%2Fpull%2F256.html)
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 …
```
> fix: minor typo in docs/index.html

- .gitignore
- docs/sections/use-case-requirements.html
> Update Identifier Discovery

- docs/openapi/openapi.yml
- docs/sections/api-spec.html
- reporting/postman_reporter/report_charts.py
- reporting/postman_reporter/report_static.py
Remove references to Profile from spec and reports
> chore: remove reference to Profile from spec and reports

- .github/workflows/onboard-rotate.yml
add-mask needs to be called immediately
> chore: fix add-mask usage

- .github/workflows/conformance-update.yml
Modify the conformance-update workflow script to first check that there are actually changes before trying to commit and push to git.
> Check diffs

- docs/openapi/schemas/Verification.yml
- docs/openapi/schemas/VerificationResult.yml
Ref https://github.com/w3c-ccg/traceability-interop/issues/176 and Tuesday's discussion.
> Verification response with `verified` and `verifications`

- tests/conformance_suite.postman_collection.json
- tests/update_conformance_schemas.sh
Add conformance testing for the `/did.json` and `/identifiers/:did` endpoints.
REF: #252 
REF: #251
> feat: conformance for /did.json and /identifiers/:did

- docs/openapi/resources/api-configuration.yml
> Remove security for did.json

- tests/conformance_suite.postman_collection.json
Renaming "Happy Path" to "Positive Testing" was suggested in #290. This PR carries that suggestion over to existing conformance tests for `credentials/issue`.
> style: rename "Happy Path" test folder in credentials/issue

- tests/conformance_suite.postman_collection.json
Add initial OAuth2 negative conformance testing for `credentials/update`
REF: #249
> feat: oauth2 conformance negative testing for credentials/update

- tests/conformance_suite.postman_collection.json
Add initial OAuth2 negative conformance testing for presentations
REF: #246
> feat: oauth2 conformance negative testing for presentations

- tests/conformance_suite.postman_collection.json
Add initial OAuth2 negative conformance testing for credentials/verify
REF: #248
> feat: oauth2 conformance negative testing for credentials/verify

- docs/index.html
based on conversations with several customers, we need more clarity on workflow definition, what credentials are required for particular workflows, and how to identify completeness of a particular workflow
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/traceability-interop/pull/318.html" title="Last updated on Jul 26, 2022, 2:59 PM UTC (1e1a898)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/traceability-interop/318/409ff5c...1e1a898.html" title="Last updated on Jul 26, 2022, 2:59 PM UTC (1e1a898)">Diff</a>
> Create a starting point for workflow completeness measurement

- docs/tutorials/agility/README.md
- docs/tutorials/authentication/README.md
- docs/tutorials/credentials-issue/README.md
- docs/tutorials/credentials-revocation/README.md
- docs/tutorials/credentials-verify/README.md
- docs/tutorials/did-web-discovery/README.md
- docs/tutorials/mill-test-report-certificate/README.md
- docs/tutorials/presentations-exchange/README.md
- docs/tutorials/presentations-verify/README.md
- docs/tutorials/vc-jwt/README.md
#100  Added instructions on how to import collection into postman
> Add "Raw" Links to Readme

- docs/tutorials/authentication/README.md
- docs/tutorials/credentials-issue/README.md
- docs/tutorials/credentials-revocation/README.md
- docs/tutorials/credentials-verify/README.md
- docs/tutorials/did-web-discovery/README.md
- docs/tutorials/presentations-exchange/README.md
- docs/tutorials/presentations-verify/README.md
Removed Empty Header for line break
https://github.com/w3c-ccg/traceability-interop/pull/323#issuecomment-1203086287
> Update README.md for Tutorials

- tests/conformance_suite.postman_collection.json
This PR adds positive conformance tests to verify that the issuer in the response to a credentials/issue request matches the issuer in the request body.
FIX: #310
> feat: test that issuer matches request

- tests/conformance_suite.postman_collection.json
This PR adds a (valid) dummy verifiable credential to the Credentials Verify folder in the Postman conformance suite.
> feat: add dummy vc to credentials verify conformance folder

- tests/conformance_suite.postman_collection.json
This PR updates conformance testing suite to rename and reorder folders to match current OpenAPI document
> style: rename and reorder conformance testing

- docs/tutorials/credentials-verify/credentials-verify.postman_collection.json
This PR fixes an improper merge from a previous PR.
Fixes #365
> fix: restore proper RFC6749 token request for tutorial tests

- package-lock.json
- package.json
- tests/README.md
- tests/conformance_suite.postman_collection.json
- tests/update_conformance_schemas.sh
- tests/update_conformance_vcs.js
- tests/valid-credential.json
This PR adds positive conformance tests for the credentials/verify endpoint and fixes the following issues;
- missing colon in keypair controller
- replace unresolvable issuer with did:key
Closes #398
Fixes #404
> chore: add positive testing for credentials/verify

- docs/openapi/openapi.yml
- docs/openapi/resources/did.yml
- docs/openapi/responses/ErrInvalidDID.yml
- docs/openapi/schemas/DidResolutionResponse.yml
- tests/conformance_suite.postman_collection.json
This PR fixes several linter errors in the OpenAPI specification.
Fixes #418
> fix: correct linter errors in openapi spec

- docs/spec/index.html
Adding guide steps for platform access via the trace interop OAS. 
I'm doing this here:
> Steps to implement oas

- docs/openapi/schemas/TraceablePresentation.yml
Remove empty `requires:` that should not have been there.
> fix: correct yaml syntax error

- tests/conformance_suite.postman_collection.json
This PR adds multi-tenant support to did web resolution and presentation endpoints.
> chore: add multi-tenant support

- tests/conformance_suite.postman_collection.json
This PR expands the negative testing for the /credentials/issue endpoint
Fixes #416
> chore: expand /credentials/issue negative testing

- tests/conformance_suite.postman_collection.json
This PR fixes one last mutation issue
> fix: fix last positive mutation test

- docs/spec/sections/authorization.html
Updating based on community feedback: https://github.com/w3c-ccg/traceability-interop/issues/401
> Updating authentication section

- .github/workflows/conformance-run.yml
- .github/workflows/interoperability-report.yml
- .github/workflows/regression-agility.yml
- .github/workflows/regression-credentials-issue.yml
- .github/workflows/regression-credentials-verify.yml
- .github/workflows/regression-did-web-discovery.yml
- .github/workflows/regression-mtrc.yml
- .github/workflows/regression-presentations-exchange.yml
- .github/workflows/regression-presentations-verify.yml
- .github/workflows/regression-vc-jwt.yml
This PR modifies existing GitHub workflows related to conformance an interoperability testing to add the new GS1 US implementation to the test suites.
> chore: add gs1us implementation to test suite

- docs/tutorials/credentials-revocation/credentials-revocation.postman_collection.json
This PR updates an additional credential verification response test so that it uses the new response shape.
Fixes #536
> fix: update verification response test

- docs/spec/index.html
> feat: add ben and nis

- docs/spec/index.html
This updates the Workflows section with normative specs and supply chain examples
> Workflows spec

- docs/spec/index.html
adds @vivienfan  to authors list
> adds vivien to authors

- docs/tutorials/agility/agility.collection.json
- docs/tutorials/authentication/authentication.postman_collection.json
- docs/tutorials/credentials-issue/credentials-issue.postman_collection.json
- docs/tutorials/credentials-revocation/credentials-revocation.postman_collection.json
- docs/tutorials/credentials-status-update/credentials-status-update.postman_collection.json
- docs/tutorials/credentials-verify/credentials-verify.postman_collection.json
- docs/tutorials/did-web-discovery/did-web-discovery.postman_collection.json
- docs/tutorials/presentations-exchange-oauth/presentations-exchange-oauth.json
- docs/tutorials/report-generation/report-tester.collection.json
- docs/tutorials/traceable-presentation-workflow/traceable-presentation-workflow.postman_collection.json
- docs/tutorials/vc-jwt/vc-jwt.collection.json
- tests/conformance_suite.postman_collection.json
This PR removes the unnecessary export fields from the postman collections. It also adds the custom user agent to the conformance suite collection.
> Remove Exporter Fields from Postman Collections

- docs/openapi/schemas/SerializedVerifiablePresentation.yml
- docs/spec/index.html
- docs/spec/sections/use-case-requirements.html
- docs/tutorials/agility/README.md
- docs/tutorials/vc-jwt/vc-jwt.collection.json
This PR removes all remaining references to vc-jws-2020
Fixes #562
> chore: remove references to vc-jws-2020

- docs/spec/index.html
@OR13 asked that I replace him as editor.
> Editor update

- docs/spec/index.html
Updating to what we actually do in the tests.
> Removes outdated DIDAuth presentation scheme

- docs/spec/index.html
> fix: remove refs to closed issues

- docs/spec/index.html
- Updates the title to correspond with content
- Proper spec references
- Bitstring instead of status list
Closes #646
> Proofing mechanism section updates

- docs/spec/sections/use-case-requirements.html
- Removes conformance-oriented endpoints, focusing on the cross-sec boundary
- Updates explanation and reference
Closes #641
> feat: service section update

- docs/spec/index.html
This closes #647. 
We might still want to add some more details for #532 (?).
> Intro reboot

- docs/spec/index.html
> removes code gen section

- docs/spec/sections/authorization.html
- docs/spec/sections/use-case-requirements.html
Closes https://github.com/w3c-ccg/traceability-interop/issues/660
> feat: holder-verifier binding

- docs/spec/index.html
> add note about VC-API

- docs/spec/index.html
> remove testing

- docs/spec/index.html
Modified Mike/Brent Editor status
> modify editors mike/brent

- docs/spec/index.html
closes https://github.com/w3c-ccg/traceability-vocab/issues/702
> cleans up credentials section

- docs/spec/index.html
- docs/spec/sections/use-case-requirements.html
Did a review of the document, cleaned up text, links, examples and references
> cleanup spec text, update links, example, and references

- docs/spec/index.html
fixes #671 to fix the last respec error by adding boilerplate conformance section.
> add conformance section
