w3c-ccg/traceability-interop

- docs/index.html
I'm sure of `Presentation` vs `Presenting`.  
I'm not sure of `proving` vs `proofing` in this context.
> fix typos introduced in #24

- docs/discovery.md
This PR removes the need to make additional network requests to discover api capabilities associated with an organization that supports the VC API.
Implementers would likely dynamically generate this `did.json` file based on the latest preferences the organization has for DIDs and their latest values... even with a DID URL present here, verification will fail if the URL is not listed in the corresponding did document.... in other words, planning for rotations in a did or even rotations of dids is a consideration when implementing this proposal.
We can consider giving the `didDocument.type` a value which makes it clear its purpose is to enable API discoverability.
> Refine proposal for discovery

- packages/tests-postman/README.md
- packages/tests-postman/index.js
Address disabled eslint rules from #44.
Note that the `eslint-disable-line import/extensions` exception when importing the sha256 module is required because the default specifier resolution of "explicit" will not locate the module without the `.js` extension. An alternative would be to require `--experimental-specifier-resolution=node` on the command line when running the tests, but that seems like an unnecessary barrier to testing.
> fix: address eslint issues in postman tests

- docs/index.html
First step at addressing #56 and #57
I expect these definitions to evolve, and likely shorten if we add a discrete section on workflows, which is likely needed as there is a lot of nuance there.  I have tried to keep things as simple and generic as possible to account for virtual and physical traceability, and to map terms back to common graph theory terms.
> doc: add definition for workflow and correlation id

- docs/openapi/openapi.yml
- docs/openapi/resources/credential-status.yml
- docs/tutorials/authenticate/README.md
- docs/tutorials/revocation/README.md
- docs/tutorials/revocation/revocable-credential.collection.json
This PR adds (back) the `updateCredentialStatus` operation from the VC API, and includes an example postman test, that is not yet wired into CI (or usable without modification).
Transmute won't support these changes until our next release, but you can use this postman test to begin to implement your support for them.
This tool should help you understand how to implement revocation list 2020:
https://api.did.actor/issue
> Add revocation example

- .github/workflows/regression-agility.yml
- docs/tutorials/agility/README.md
- docs/tutorials/agility/agility.collection.json
cc @msporny this PR adds the suite agility test here.
it requires authentication to be turned on, and it makes use of a resolver endpoint... which is required to discover the issuer keys for a did:web.
Happy to explain more about that if you like.
See also this:
https://github.com/w3c-ccg/traceability-interop/blob/main/docs/discovery.md
(we are dropping support for the DIF Well Known did config in favor of did web discovery)
> Add suite agility test

- .github/workflows/regression-exchange.yml
- docs/tutorials/exchange/README.md
- docs/tutorials/exchange/exchange-tutorial.collection.json
This tutorial shows how to issue a Verifiable Business Card for a vendor that supports the VC API.
Then get the domain and challenge from them, and sign a presentation for them, and submit the presentation.
The current flow is all with 1 party, but a subsequent flow can be created that demonstrates a multiparty exchange.
> Add exchange tutorial

- docs/openapi/openapi.json
- docs/openapi/openapi.yml
Spoke offline with @OR13 about updating the DID resolution endpoint path to match what is being tested in the postman tests:
- Old: `/{did}`
- New: `/identifiers/{did}`
> chore: update DID resolution endpoint to match postman testing

- docs/openapi/openapi.json
The `openapi.json` had not been recently updated. I ran `npm run preserve` to remove references to Pet and bring the file up to date.
> fix: openapi.json should be up to date with latest changes in yml

- .github/workflows/authentication-tutorial.yml
- .github/workflows/regression-agility.yml
- .github/workflows/regression-did-web-discovery.yml
- .github/workflows/regression-exchange.yml
- .github/workflows/regression-mtrc.yml
- .github/workflows/regression-revocation.yml
- .github/workflows/regression-vc-jwt.yml
The default behavior of github workflows when one path of a matrix test fails is to halt all other paths and stop the tests. In the case of this repository, that behavior is not ideal (one provider failing a test should not prevent other providers from being tested).
The solution to this issue is to disable the default `job.<job_id>.strategy.fail-fast`.
> Disable "fail-fast" for all matrix workflows

- .github/workflows/publish-openapi-spec.yml
This probably needs some testing and tweaking to ensure that
a) it works properly - holding off on this for merge freeze prior to today's call
b) other gh publishing jobs don't overwrite it  - we may want to add a `workflow_call` event and call this from the daily scheduled interop test OR modify that test to only deploy the /docs/reports subfolder.
> Add workflow to just build/publish OpenAPI spec

- docs/openapi/index.html
- docs/openapi/resources/credential-issuer.yml
- docs/openapi/responses/BadRequest.yml
- docs/openapi/responses/_index.yml
- docs/openapi/schemas/Credential.yml
- docs/openapi/schemas/Error.yml
- docs/openapi/schemas/IssueCredentialOptions.yml
- docs/openapi/schemas/Presentation.yml
- docs/openapi/schemas/RevocationListCredential.yml
Related conversations:
- https://github.com/w3c-ccg/vc-api/issues/274
- https://github.com/w3c-ccg/vc-api/issues/266
- https://github.com/w3c-ccg/vc-api/issues/267
- https://github.com/w3c-ccg/vc-api/issues/265
In order to merge this pull request, we need unanimous agreement to the following:
1. That a 400 error shall be thrown for all attempts to issuer a credential without providing an issuer.
2. That a 201 shall be returned when the requested issuer can be used to sign the credential
> Make issuer required when issuing credential

- docs/openapi/openapi.yml
- docs/openapi/resources/api-configuration.yml
- docs/openapi/resources/credential-issuer.yml
- docs/openapi/resources/credential-status.yml
- docs/openapi/resources/credential-verifier.yml
- docs/openapi/resources/credential.yml
- docs/openapi/resources/did.yml
- docs/openapi/resources/presentation-available.yml
- docs/openapi/resources/presentation-prover.yml
- docs/openapi/resources/presentation-submissions.yml
- docs/openapi/resources/presentation-verifier.yml
- docs/openapi/resources/presentations.yml
- docs/openapi/responses/Unauthenticated.yml
- docs/openapi/responses/Unauthorized.yml
- Added scopes from https://github.com/w3c-ccg/traceability-interop/issues/124
- Assigned to endpoints
- Added 401 and 403 errors
> Added scopes, endpoint security and errors

- docs/openapi/openapi.yml
`/api` seems unnecessary. It is also inconsistently implemented.
> feat: removal of /api from path

- .github/workflows/regression-workflow-instance-join.yml
- docs/tutorials/workflow-join/workflow-instance-join.collection.json
I stored some variables to the environment in this collection. I think that has caused some failures when run in parallel actions alongside other collections. So this isolates the collection to only using collectionVariables. 
Also I've changed the request names to the common conventions which should make it look better in the report.
> fix: keep variables in collection only

- docs/openapi/schemas/DidResolutionResponse.yml
Update the YAML for DID resolution response so that `alsoKnownAs` must be an array of strings with at least two elements, and service must be a non-empty array with objects that contain type and serviceEndpoint string properties. Note that it does not seem possible to require that one of the service elements contain a serviceEndpoint.type property with the value "TraceabilityAPI" while using OAS v3.0.0
FIXES: #118
> fix: update OpenAPI yaml for DID resolution response

- .github/workflows/interoperability-report.yml
Only publish reports if the workflow was triggered from the main branch.
FIXES: #224
> feat: only publish reports from main branch

- docs/tutorials/presentations-exchange/presentations-exchange.postman_collection.json
The request for `Get Organization DIDs (Issuer)` sets the value for `credential_issuer_id` on [line 236](https://github.com/w3c-ccg/traceability-interop/blob/f274bdb7aeff5cef812352180b4227b910d1ecda/docs/tutorials/presentations-exchange/presentations-exchange.postman_collection.json#L236).
This value is then later overwritten by the `Get Organization DIDs (Verifier)`  call which overwrites the `credential_issuer_id` with the the verifier's `did:key`, which is what this PR addresses. 
```
→ Issue Credential
POST {{BASE_API_URL}}/credentials/issue  
400 Bad Request ★ 2s time ★ 1.65kB↑ 445B↓ size ★ 10↑ 8↓ headers ★ 0 cookies
┌ ↑ raw ★ 551B
│ {
│     "credential": {
│         "@context": [
│             "https://www.w3.org/2018/credentials/v1"
│         ],
│         "id": …
```
> Fix Presentation Exchange Collection

- docs/index.html
There are no standard implementations.
Adding excessive "early stage experimental stuff" harms the usability of the profile and make its harder to understand.
If we are not intending to test it, we ought not to include it.
We are currently not intending to test either BBS+ or Merkle Disclosure Proofs.
I suggest we remove both until we have added support for them and agreed to test them.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/traceability-interop/pull/235.html" title="Last updated on May 19, 2022, 5:55 PM UTC (3a7c36f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/traceability-interop/235/60d5df4...3a7c36f.html" title="Last updated on May 19, 2022, 5:55 PM UTC (3a7c36f)">Diff</a>
> Remove Merkle Proof Selective Disclosure

- docs/tutorials/presentations-exchange/presentations-exchange.postman_collection.json
Remove the now deprecated test that was persisting collection variable for credential_issuer_id.
FIXES: #234
> fix: remove deprecated test for persisting unused value

- docs/tutorials/presentations-verify/presentations-verify.postman_collection.json
PR #260 updated the "Get Organization DIDs (Verifier)" request to use bearer auth, but used the `{{issuer_access_token}}` instead of the `{{verifier_access_token}}`.
This PR updates the request to use the proper token.
> fix: use correct bearer token for verifier did resolution

- docs/openapi/responses/BadRequest.yml
- docs/openapi/responses/Unauthenticated.yml
- docs/openapi/responses/Unauthorized.yml
Currently, the [response schema for errors](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/Error.yml) includes an integer `code`, a string `message`, and an object `details`.
This PR adds support for defining specific values for `code` and `message` values in the OpenAPI spec, and leaves the `details` object up to the implementor.
REF: #41
> feat: add specific error response messages to spec

- .github/workflows/conformance-run.yml
- .github/workflows/interoperability-report.yml
- README.md
Add nightly scheduled conformance report suite. The resulting published report will contain MANY tests, and is currently being published separately from the interoperability report.
FIX #265
> Schedule conformance report suite

- README.md
Add a badge to the repository `README.md` file to display conformance test suite status.
> docs: add conformance suite badge to README.md

- .github/workflows/test-suite-registration.yml
- README.md
New workflows can't be tested if they are not present on `main`.
REF: #261
> Add onboard workflow to main

- AGENDA.md
- README.md
Add ADENDA.md to repository so that it can be linked during meetings, and update README.md to include more detailed hosting instructions.
> docs: update hosting instructions, add AGENDA.md

- tests/conformance_suite.postman_collection.json
Add a string to conformance requests for /credentials/issue so that they can be more easily identified in test output.
FIX: #270
> style: namespace /credentials/issue conformance requests

- docs/openapi/resources/credential.yml
I'm fairly sure this is the right syntax for optional security. The swagger editor accepts it too:
> Optional security for public credentials

- reporting/postman_reporter/report_charts.py
- reporting/postman_reporter/report_config.py
- reporting/postman_reporter/report_data.py
* Update size of boxes in facet report to prevent overlapping
* Color pass/fail based on number of assertions passed or failed
* Clean up tooltips on facet report
FIX: #278
> chore: reporting updates and fixes

- docs/openapi/schemas/TraceabilityAPIDIDWebDocument.yml
This PR updates the openapi schema spec for the traceability API DID Web Document to match the did-core spec by allowing `@context` to be a string or an array containing string or object type items.
FIX: #282
> chore: update schema for did document @context

- .github/workflows/conformance-run.yml
- .github/workflows/interoperability-report.yml
- reporting/README.md
- reporting/postman_reporter/report_config.py
- reporting/postman_reporter/report_data.py
- reporting/reporter.py
This PR modifies the `reporter.py` script to accept one of two new command line options, `--conformance (-c)` and `--interoperability (-i)`. These options allow the script the automatically download test suite output from the appropriate subfolder of `https://w3id.org/traceability/interoperability/reports` when not running in `ci` mode.
Additionally, this facilitates a solution to #272 by allowing the script to choose an appropriate HTML template do differentiate between conformance and interoperability reporting.
FIX: #302
> feat: add flags to specify report type

- docs/openapi/schemas/PresentationOptions.yml
This PR makes the `challenge` property of [PresentationsOptions.yml](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/PresentationOptions.yml) required.
FIX: #259
> feat: require 'challenge' property in prove presentation options

- tests/conformance_suite.postman_collection.json
This PR adds negative tests to ensure that providers return `400 Bad Request` if the issuer ID in a `credentials/issue` request is a string but is not in uri format.
FIX: #294
> feat: add issuer id uri tests for credentials/issue

- tests/conformance_suite.postman_collection.json
- tests/update_conformance_schemas.sh
Current name of variable used to store JSON schema for validation on 201 responses for the /credentials/issue endpoint is `responseSchema201`. Preventing future clashes with other 201 responses that require validation, e.g., `/presentations/prove`, by renaming to `responseSchema201CredentialsIssue`.
> fix: rename responseSchema201

- docs/openapi/resources/presentation-available.yml
- docs/openapi/resources/presentation-submissions.yml
`/presentations/available` and `/presentations/submissions` are specified with `security: []`. While that does seem like a way to explicitly state that security is not allowed, the OAS doesn't seem to understand it, showing a lock for those endpoints: 
This PR removes `security: []`, which is also how we specified [getTraceabilityAPIConfiguration](https://w3c-ccg.github.io/traceability-interop/openapi/#get-/did.json).
> Fix how endpoints without security is specified

- docs/openapi/schemas/Error.yml
- tests/conformance_suite.postman_collection.json
Currently, the error schema requires the details member to be an object with arbitrary properties.
This PR relaxes the error schema to allow the details member to be a string, an array of strings, or an object with arbitrary properties.
> Flexible error details

- tests/conformance_suite.postman_collection.json
This PR fixes a typo in variable name used when populating the request body for auth-related negative testing for the `/credentials/issue` endpoint.
> chore: correctly populate request body

- tests/conformance_suite.postman_collection.json
This PR fixes the name of the negative missing scope auth test for `/credentials/verify` endpoint.
> chore: fix test naming

- tests/conformance_suite.postman_collection.json
This PR adds stubs for conformance testing of the following endpoints:
* `/presentations/prove`
* `/presentations/verify`
* `/presentations/available`
* `/presentations/submissions`
This includes negative auth testing for `/presentations/prove` (#245) and `/presentations/verify` (#244). The folders for `/presentations/available` and `/presentations/submissions` are just empty stubs that will help prevent conflicts in the postman file when they are implemented in separate pull requests later.
> chore: add conformance test stubs for remaining endpoints

- tests/conformance_suite.postman_collection.json
This PR validates that the `credentialSubject` returned from a `credentials/issue` request matches the `credentialSubject` provided in the request body.
FIX: #313
> chore: test that subject matches request

- tests/conformance_suite.postman_collection.json
This PR adds negative testing to ensure that an issuer does not issue a credential if it does not have key materials for the requested "credential.issuer".
FIX: #311
> chore: add negative testing for unknown issuers

- tests/conformance_suite.postman_collection.json
This PR updates existing conformance testing to reflect the updates from PR #288 (`issuer.id` is now required when `issuer` is in object format).
FIX: #338
> feat: update tests to reflect required nature of issuer.id property

- tests/conformance_suite.postman_collection.json
This PR validates that the `issuanceDate` in the reponse to `credentials/issue` matches the `issuanceDate` in the request.
FIX: #314
> chore: test issuanceDate matches requested value

- docs/openapi/resources/did.yml
- docs/openapi/responses/NotFound.yml
- tests/conformance_suite.postman_collection.json
- tests/update_conformance_schemas.sh
This PR add a generic `404` error to the OpenAPI schema and to the set of responses for `/identifiers/:did`, as well as an endpoint-specific `400` error for `/identifiers/:did` with a custom message.
FIX: #289
> chore: additional responses for did resolution

- reporting/postman_reporter/report_charts.py
This PR adjusts the facet figure in generated reports so that the height is dynamic based on the number of rows. This is required in order to prevent overlapping marks as the number of rows increases.
NB: we may need to adjust this slightly once all rows have been added to conformance testing, as there seems to be a slight drift in heights when more rows are present.
FIX: #315
> feat: make facet chart height dynamic

- reporting/assets/conformance.j2
- reporting/assets/interoperability.j2
- reporting/postman_reporter/report_config.py
- reporting/reporter.py
This PR updates the report generation system to use separate templates for conformance and interoperability reports, and modifies the report titles to differentiate between the two. This change makes it easier for the reports to diverge as needed.
FIX: #272
> chore: split report template by report type

- reporting/reporter.py
This PR fixes a code path related to CI which requires runtime arguments to be threaded through the call stack to the `runHtml()` function call.
> fix: runtime args must be threaded through ci mode invocation

- docs/tutorials/agility/agility.collection.json
- docs/tutorials/authentication/authentication.postman_collection.json
- docs/tutorials/credentials-issue/credentials-issue.postman_collection.json
- docs/tutorials/credentials-revocation/credentials-revocation.postman_collection.json
- docs/tutorials/credentials-verify/credentials-verify.postman_collection.json
- docs/tutorials/did-web-discovery/did-web-discovery.postman_collection.json
- docs/tutorials/mill-test-report-certificate/vc-api.mtrc.collection.json
- docs/tutorials/presentations-exchange-oauth/presentations-exchange-oauth.json
- docs/tutorials/presentations-exchange/presentations-exchange.postman_collection.json
- docs/tutorials/presentations-verify/presentations-verify.postman_collection.json
- docs/tutorials/vc-jwt/vc-jwt.collection.json
- docs/tutorials/workflow-join/workflow-instance-join.collection.json
This pull request updates existing Postman interoperability tutorial suites to use proper RFC 6749 token requests (#350) and adds the required scopes to the request (#356)
> fix: use proper RFC 6749 token request for tutorial tests

- .github/workflows/conformance-run.yml
- .github/workflows/interoperability-report.yml
This PR modifies existing GitHub workflows that publish nightly reports to add a step that stores the reports in a timestamped folder for archival purposes.
Conformance and Interoperability reports continue to be published to the `reports/conformance` and `reports/interoperability` GitHub pages subfolders respectively, and are now also published to `reports/conformance-XXXXXXXXXX` and `reports/interoperability-XXXXXXXXXX` subfolders (where XXXXXXXXXX is the current unix epoch timestamp at the time of publishing).
This PR addresses long-term storage of the nightly scheduled reports, but it does NOT generate a browsable index. That work will still need to be completed, possibly in a separate ticket.
REF: #199
> feat: begin publishing archived reports

- docs/openapi/resources/credential-status.yml
This PR is an implementation of the proposed changes from #358, namely making the OpenAPI definition for `credentials/status` request bodies more strict.
fixes #358
> chore: clarify request body for credentials status request

- tests/conformance_suite.postman_collection.json
This PR adds some explicit bad type checks for `credential.proof` in the request body for the `/credentials/verify` endpoint. Adding these checks to iterate over the possible bad types exposed some errors in our implementation, and should have been included in the testing from the start.
> tests: add explicit bad type checks

- tests/conformance_suite.postman_collection.json
Update the `credentialSubject` positive test for `/credentials/issue` to take into account the required object-with-optional-id format.
Fixes #393
> fix: update credential subject positive test

- docs/openapi/resources/credential-verifier.yml
This PR implements the changes discussed in #360 to make the `verifiableCredential` property a required part of the `/credentials/verify` request body. Previously, this was an optional property.
Fixes #360
> fix: required verifiableCredential property in credentials/verify

- docs/openapi/schemas/Error.yml
- tests/conformance_suite.postman_collection.json
This removes some of the asserted details from the responseSchema40x schemas: 
- `code` which seems redundant with the actual status code (see https://github.com/w3c-ccg/traceability-interop/issues/381).
- the precise error message, which is also redundant as it just describes the generic error http error.
> Removing code and message from responseSchema40x schemas

- docs/spec/sections/use-case-requirements.html
This PR removes references to alsoKnownAs from the respec doc in this repo.
References #389
> docs: remove alsoKnownAs references from respec

- docs/openapi/schemas/IssueCredentialOptions.yml
- tests/conformance_suite.postman_collection.json
This PR makes the `credentialStatus.type` property required (when `credentialStatus` is present) in the `options` object when posting to `/credentials/issue`.
This change is driven by the vc-api specification as outlined in #395 
Fixes #395
> chore: require type property for credentialStatus

- docs/openapi/resources/presentations.yml
This PR adds a description to the OpenAPI schema for the `POST` request in the `/presentations` endpoint.
Fixes #369
> docs: add description to /presentations endpoint schema

- tests/conformance_suite.postman_collection.json
This PR removes the negative testing related to bad values in `proof.created` (see #428), and adds positive testing to check that the `proof.created` value returned from a post to `/credentials/issue` is within 10 seconds of the current time.
Fixes #352
References #351
> feat: test proof created date within 10s

- .github/workflows/publish-openapi-spec.yml
This PR updates the GitHub workflow that publishes the OpenAPI spec to GitHub Pages to add a step for linting.
Fixes #420
> feat: add openapi linting to ci process

- tests/conformance_suite.postman_collection.json
This PR fixes a bug in the positive tests for `/credentials/issue` where a change to the way request body is mutated was not carried over from the negative tests.
> fix: update positive tests to use mutation

- docs/openapi/schemas/IssueCredentialOptions.yml
- tests/conformance_suite.postman_collection.json
This PR adds negative testing for the `options.created` property in a `/credentials/issue` request. Specifically, it ensures that the optional value is a valid XML Date Time String.
A positive test has also been added to ensure that the value of `proof.created` in the response body matches the given value of `options.created`.
Fixes #428
> feat: add negative testing for options.created

- tests/conformance_suite.postman_collection.json
This PR adds two requests that will be executed before the conformance requests. These two new requests will remove any existing `didWebCache` and `tokenCache`. These requests can also be used manually to clear the respective caches on-demand, e.g., during testing.
> feat: add cache-clearing requests

- .github/workflows/conformance-run.yml
- .github/workflows/interoperability-report.yml
New Ubuntu runner image version 20221027.1 upgrades to python 3.11, which causes some issues with module installs.
This PR updates the configuration for `actions/setup-python@v4` in the interop and conformance workflows to pin python to `3.10` instead of `3.x`.
Fix: #458
> fix: pin python to 3.10 in actions

- README.md
This PR updates documentation for moderating meetings to include posting agenda to the public-credentials mailing list and to streamline the existing instructions.
Fixes #371
Fixes #439
> docs: update docs on meeting procedures

- .github/workflows/publish-report-index.yml
- README.md
- docs/reports/archive/index.html
This PR adds an index for historical test suite results and updates the main `README.md` to link to it.
Fixes #364
> docs: add historical report archive

- tests/conformance_suite.postman_collection.json
This PR adds a test to ensure that an otherwise well-formed verification request with an incorrect JWS signature returns a 200 response with `verified:false`.
Additionally, existing "positive" testing has been updated to validate that the response contains `verified:true`.
Fixes #431
> chore: add bad signature testing

- docs/openapi/schemas/Credential.yml
- docs/openapi/schemas/Presentation.yml
- docs/openapi/schemas/RevocationListCredential.yml
- docs/openapi/schemas/SerializedVerifiableCredential.yml
- docs/openapi/schemas/SerializedVerifiablePresentation.yml
- docs/openapi/schemas/TraceablePresentation.yml
- docs/openapi/schemas/VerifiableCredential.yml
- docs/openapi/schemas/VerifiablePresentation.yml
- tests/conformance_suite.postman_collection.json
- tests/traceability-v1.jsonld
- tests/update_conformance_vcs.js
- tests/valid-credential.json
This PR adds negative testing to ensure failure when a credential presented to `/credentials/issue` does not contain the required context entry, as well as positive testing that fails if a response to `/credentials/issue` contains a verifiable credential without the required context entry.
Fixes #474
> chore: add tests for `@context` entry

- docs/openapi/schemas/Verification.yml
- docs/openapi/schemas/VerificationResult.yml
- tests/conformance_suite.postman_collection.json
This PR makes the `verifications` array in the [VerificationResult.yaml](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/VerificationResult.yml) object required. The array can be empty, but it must be present.
Additionally, `Signature` has been added as an enum value for the `title` property of a `verifications` array item, `status` values `good` and `bad` have been changed to `Passed` and `Failed` respectively, and an entry for each of the possible `title` enum values has been added to the example verification result.
Fixes #469
Fixes #470
> chore: make verifications required in verification result

- docs/tutorials/credentials-revocation/credentials-revocation.postman_collection.json
- docs/tutorials/credentials-verify/credentials-verify.postman_collection.json
- docs/tutorials/mill-test-report-certificate/vc-api.mtrc.collection.json
- docs/tutorials/presentations-exchange/presentations-exchange.postman_collection.json
- docs/tutorials/presentations-verify/presentations-verify.postman_collection.json
- docs/tutorials/report-generation/report-tester.collection.json
- docs/tutorials/workflow-join/workflow-instance-join.collection.json
This PR fixes a regression caused when the responses to `/credentials/issue` and `/presentations/prove` started being nested under top-level `verifiableCredential` and `verifiablePresentation` elements respectively.
Fixex #488
> fix: store nested VC and VP data for later use

- docs/spec/index.html
Corrects some formatting on HTML.
Reorders sections for better readability.
Adds section around business rules handling for identifiers and common operations performed using external systems with data receiving or analyzing data presented using this spec
> Feature/operations handling, Business Rules

- docs/openapi/resources/credential.yml
I don't see why getCredential 404 shouldn't be pulling from the common NotFound error. Seems inconsistent. 
Ref https://github.com/w3c-ccg/vc-api/pull/326
> Get credential error schema

- .github/workflows/conformance-run.yml
This PR removes the legacy MESUR_IO_DEV implementation from conformance testing.
> build: remove MESUR_IO_DEV from conformance suite

- tests/conformance_suite.postman_collection.json
This PR ensures that negative authentication and authorization tests only fail for one reason. There were several tests that were not updated after we implemented request body mutation, and these were still trying to reference old (removed) variables resulting in an empty request body.
Other tests (presentation related) were not sending any request body at all and have been upgrade to start using request body mutation with the current behavior to send an empty JSON object.
> fix: add request bodies to negative tests

- docs/spec/index.html
This PR adds email addresses for the spec editors.
---
Fixes #492
> docs: add editor email addresses

- tests/conformance_suite.postman_collection.json
- tests/conformance_suite.postman_environment.json
This PR seeks to resolve issue #457 by relaxing the scope-related requirements for conformance via the following changes:
* Conformance testing no longer requires that OAuth2 providers grant ONLY those scopes requested
* Conformance testing no longer requires that specific scopes be present in order to pass testing
* Default behavior assumes that OAuth2 provider includes _all_ scopes granted to a client ID in the JWT token
* Override behavior allows implementations to provide a list of scopes that client should request via the `CLIENT_SCOPE` configuration variable.
A brief summary of code changes:
* All tests for `missing_scope` have been removed.
* Tests which require authentication no longer individually specify which scopes should be requested
* Sample environment configuration now …
> refactor: relax specific scope naming requirements

- reporting/assets/conformance.j2
- reporting/assets/interoperability.j2
- reporting/postman_reporter/report_static.py
- reporting/postman_reporter/reporter_util.py
This PR moves inline CSS into the existing `style` block in the HTML header for generated test reports. This change results in a size decrease for the two generated HTML files from about 21MB to about 1MB nightly.
Fixes #547
> refactor: remove inline CSS

- tests/conformance_suite.postman_collection.json
This PR updates the traceability conformance tests to be compatible with the [Status List 2021 spec](https://www.w3.org/TR/vc-status-list/), as discussed in https://github.com/w3c-ccg/traceability-interop/pull/555 and mandated by the [current Trace Interop spec](https://w3c-ccg.github.io/traceability-interop/draft/#data-integrity-proof-suites).
For implementations which do not support Status List 2021, these changes will cause some tests to fail within the `Credentials - Create` and `Credentials - Update Status` Postman collections.
> Update conformance tests to use status list 2021

- docs/openapi/responses/BadRequest.yml
- docs/openapi/responses/ErrInvalidDID.yml
- docs/openapi/responses/ErrUnknownIssuer.yml
- docs/openapi/responses/NotFound.yml
- docs/openapi/responses/Unauthenticated.yml
- docs/openapi/responses/Unauthorized.yml
- tests/conformance_suite.postman_collection.json
We had a prior agreement on a call, that we should specify the shape of the errors, but we do not need to specify the exact value of the error message.
> removes requirement of messages to be a specific enum

- docs/openapi/parameters/header/accept.yml
- docs/openapi/parameters/header/contentType.yml
- docs/openapi/resources/credential-verifier.yml
`Content-type` is a standard header, and fits this use case.
> feat: change vc-format header to content-type

- docs/tutorials/traceable-presentation-workflow/traceable-presentation-workflow.postman_collection.json
This PR adds a missing `audience` key to the request body for getting a token in the workflow tutorial.
> fix: add token audience for workflow tutorial

- docs/tutorials/agility/agility.collection.json
- docs/tutorials/authentication/authentication.postman_collection.json
- docs/tutorials/credentials-issue/credentials-issue.postman_collection.json
- docs/tutorials/credentials-revocation/credentials-revocation.postman_collection.json
- docs/tutorials/credentials-status-update/credentials-status-update.postman_collection.json
- docs/tutorials/credentials-verify/credentials-verify.postman_collection.json
- docs/tutorials/did-web-discovery/did-web-discovery.postman_collection.json
- docs/tutorials/presentations-exchange-oauth/presentations-exchange-oauth.json
- docs/tutorials/traceable-presentation-workflow/traceable-presentation-workflow.postman_collection.json
- docs/tutorials/vc-jwt/vc-jwt.collection.json
This PR updates the `scope` body parameter to use an environment variable instead of hard-coded scope names per #457.
As a reminder, it is now assumed that OAuth providers will return *all* scopes granted to the client ID in use when no scope is named in the token request (the default behavior for many providers, e.g. Auth0), and that implementations which require a value to be present in the token request (e.g., Azure) must provide a value for the `CLIENT_SCOPE` environment variable.
Fixes #550
> chore: remove scope from interop suite

- .github/workflows/interoperability-report.yml
This PR ensures that values from repository secrets are passed for the CLIENT_SCOPE environment variables for interop testing.
> fix: pass scope in env var

- tests/conformance_suite.postman_collection.json
Closes https://github.com/w3c-ccg/traceability-interop/issues/586.
> Fill illegal empty subject in tests

- docs/spec/index.html
This cleans up redundant specifications of workflows, moving the definitions to vocab (as agreed: https://github.com/w3c-ccg/traceability-interop/issues/502). 
The good parts I've copied over to vocab here: https://github.com/w3c-ccg/traceability-vocab/pull/856. 
Closes https://github.com/w3c-ccg/traceability-interop/issues/502
Closes https://github.com/w3c-ccg/traceability-interop/issues/485
> Bringing together scattered workflow NDRs, moving it to vocab

- docs/tutorials/agility/agility.collection.json
- docs/tutorials/authentication/authentication.postman_collection.json
- docs/tutorials/credentials-issue/credentials-issue.postman_collection.json
- docs/tutorials/credentials-revocation/credentials-revocation.postman_collection.json
- docs/tutorials/credentials-status-update/credentials-status-update.postman_collection.json
- docs/tutorials/credentials-verify/credentials-verify.postman_collection.json
- docs/tutorials/did-web-discovery/did-web-discovery.postman_collection.json
- docs/tutorials/presentations-exchange-oauth/presentations-exchange-oauth.json
- docs/tutorials/report-generation/report-tester.collection.json
- docs/tutorials/traceable-presentation-workflow/traceable-presentation-workflow.postman_collection.json
- docs/tutorials/vc-jwt/vc-jwt.collection.json
Issue: https://github.com/w3c-ccg/traceability-interop/issues/567
This PR updates the postman collections so all of the requests will use `W3C Traceability Interop Tests` as the `user-agent`.
> Postman Tests Use Custom User Agent

- docs/spec/index.html
This PR adds a "Code Generation" section to the respec document, with example and links for typescript client code generation from the OpenAPI specification.
Fixes #503
> docs: add code generation section to respec

- tests/conformance_suite.postman_collection.json
This PR adds a negative conformance test for duplicate JSON key `issuer` in a credentials issue request. The expectation is that the issuer will return a 400 error response.
This test is added into a new sub-folder called "Duplicate Keys" because any tests like this will differ from our standard tests in that it is not a simple mutation of the minimal request JSON object (you can't add duplicate keys in JSON). If we add more tests here,  each one will have a request body in raw text (not JSON) that includes the minimal credentials issue request with the appropriate key duplicated.
When we discuss this on call, we should determine whether or not we feel we need duplicate key tests for all keys.
Fixes #539
> chore: add test for duplicate issuer value

- README.md
Remove quotes that were breaking interop meetings link.
> docs: fix interop meetings link

- docs/spec/index.html
This PR adds links to the respec document so that users can find the tutorials on importing and running Postman interoperability and conformance testing suites.
Fixes #460
> chore: add postman documentation to respec

- docs/openapi/parameters/header/accept.yml
- docs/tutorials/credentials-issue/README.md
- docs/tutorials/credentials-issue/credentials-issue.postman_collection.json
- docs/tutorials/credentials-revocation/credentials-revocation.postman_collection.json
- docs/tutorials/credentials-status-update/credentials-status-update.postman_collection.json
- docs/tutorials/credentials-verify/credentials-verify.postman_collection.json
- docs/tutorials/vc-jwt/vc-jwt.collection.json
- tests/conformance_suite.postman_collection.json
This PR updates references to `Accept` header in "Create Credentials" requests to use either `application/vc+ld+json` or `application/vc+ld+json+sd-jwt`, as discussed in issue https://github.com/w3c-ccg/traceability-interop/issues/574.
EDIT: using `application/sd-jwt` rather than `application/vc+ld+json+sd-jwt`, as discussed in 11/7/23 trace call.
> Update Accept header to application/vc+ld+json

- tests/conformance_suite.postman_collection.json
Replaced occurrences of `credentialstatus` with` credentialStatus` for the conformance prerequests. This was resulting in an incorrect key being used in the request for testing.
> `credentialStatus` prerequest scripts create an additional array with the key `credentialstatus` (all lowercase)

- docs/spec/sections/abstract.html
closes #528 
Got kind of stuck writing this, would love any improvements or suggestions.
> changes to abstract

- docs/spec/index.html
- docs/spec/sections/abstract.html
The markdown reference in the abstract is broken. This fixes that, moving the reference to a proper biblio entry.
> VC Reference

- .github/workflows/interoperability-report.yml
This PR is related to #482. The interoperability reporting GA currently tests the RevocationList2020, I would like to propose a change test revocation with StatusList2021 instead.
> change collection link to use the StatusList2021 collection

- docs/spec/sections/use-case-requirements.html
- Removes the DID-based authentication
- Makes `assertionMethod` mandatory (at least one, referencing a `verficationMethod`)
- Makes `verificationMethod` mandatory (at least one)
- Replaces example `did:key` with `did:web`
- Adds `verificationMethod` to the example
Closes #642 
Closes #643
> 642 assertionmethod section seems unnecessary

- docs/spec/sections/authorization.html
This still had reminiscences of supporting multiple ways to authenticate. This should make it more readable. 
Title updated to Authentication, which is what the section is actually about. (Note that I have not updated references and file name to avoid merge collisions - to be updated in a later PR). 
Closes #644.
> fix: presentation authentication section
